baseURL = "https://giacomodreams.netlify.app/"
languageCode = "en-us"
title = "giacomo dreams"
theme = "my-first-theme"

[params]
	instagram = 'giacomodreams'


	
[menu]

	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 10


